### ISSUE TITLE
No connection without RP

### ISSUE THREAD

**Issue by PlexN** [ExtensiveAutomation/extensiveautomation-appclient#1]
### Description of the issue
Hi Denis,

I tried to connect to my server through the client (portable mode) without RP. 
I followed the steps mentionned to modify the settings.ini but when I provide the server address without a port, the app loops trying to connect. 
If I enter a port after the address (8082), it's the same behaviour.

- output.log when no port is provided 

![appclient](https://user-images.githubusercontent.com/28578204/61642179-c6b4e700-aca0-11e9-894b-4950503c09b0.PNG)

- output.log when the port 8082 is provided 

ERROR - EventServerInterface > error: [TcpClientThread]: ('XXX.XXX.XXX.XXX', XXXXX) more data needed for ws handshake: need more ws headers on request

### Steps to reproduce the issue

1. Have a server (Docker version or Linux)
2. Modify the settings.ini as mentionned in the README
3. Try to connect without a port in the address
4. Try to connect with the port 8082 in the address

### Additionnals informations like versions, logs, screenshots

extensiveautomation-server : 20.0.0
extensiveautomation-appclient: 20.0.0
python:2.7

**Comment by dmachard** [comment]
If you provide a tcp port in the address, the application overwrites the settings file (in your case the config has been reverted to the reverse proxy mode)

On client side, can you retry to update the settings file manually like explained in the README (a key to change too was missing) and reconnect to the server without providing the port in the address ?  

  [Server]
    data-ssl=False
    api-ssl=False
    port-data=8082
    port-api=8081
    rest-path=/

On server side, if you have a firewall runnning on the server, don't forget to authorize from outside the tcp/8081 and tcp/8082 port . Can you run the following command and paste the output here ?

curl -X POST http://127.0.0.1:8081/session/login -H "Content-Type: application/json" -d '{"login": "admin", "password": "password"}'

**Comment by PlexN** [comment]
Denis,

Adding the missing key "api-ssl=False" resolved the problem. I could connect to the server, without providing the port.

I tried on a fresh install of the server and also with the docker version, both work.

Thank you
